
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.minustserv.ArrayOfSubjectData;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ISubjects", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.minustserv.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ISubjects {


    /**
     * 
     * @param unp
     * @return
     *     returns ArrayOfSubjectData
     */
    @WebMethod(operationName = "GetSubjectData", action = "http://tempuri.org/ISubjects/GetSubjectData")
    @WebResult(name = "GetSubjectDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSubjectData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSubjectData")
    @ResponseWrapper(localName = "GetSubjectDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSubjectDataResponse")
    public ArrayOfSubjectData getSubjectData(
        @WebParam(name = "unp", targetNamespace = "http://tempuri.org/")
        Integer unp);

    /**
     * 
     * @param name
     * @return
     *     returns ArrayOfSubjectData
     */
    @WebMethod(operationName = "GetSubjectDataName", action = "http://tempuri.org/ISubjects/GetSubjectDataName")
    @WebResult(name = "GetSubjectDataNameResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSubjectDataName", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSubjectDataName")
    @ResponseWrapper(localName = "GetSubjectDataNameResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSubjectDataNameResponse")
    public ArrayOfSubjectData getSubjectDataName(
        @WebParam(name = "name", targetNamespace = "http://tempuri.org/")
        String name);

}
